
import java.awt.Font;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Brandon Coleman
 */
public class Resume extends javax.swing.JFrame {

    String temp = "";
    int mode = 1;

    /**
     * Creates new form Resume
     */
    public Resume() {
        initComponents();
        StyledDocument doc = Output.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        Output.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void out(String text) {
        temp = temp + text + "\r\n";
        Output.setText(temp);
    }

    private void dashes(String text) {
        temp = temp + "----------" + text + "----------\r\n";
        Output.setText(temp);
    }

    private void lf() {
        temp = temp + "\r\n";
        Output.setText(temp);
    }

    private void clearOutput() {
        Output.setText("");
        temp = "";
    }

    private void changeTheme() {
        mode++;
        switch (mode) {
            case 1:

                break;
            case 2:

                break;
            case 3:

                break;
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btn_Intro = new javax.swing.JButton();
        btn_Education = new javax.swing.JButton();
        btn_EducationalExp = new javax.swing.JButton();
        btn_Goals = new javax.swing.JButton();
        btn_WorkHistory = new javax.swing.JButton();
        btn_ProfessionalExp = new javax.swing.JButton();
        btn_About = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Output = new javax.swing.JTextPane();
        btn_Code = new javax.swing.JButton();
        btn_Theme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("AcmeFont", 0, 18)); // NOI18N
        title.setText("Brandon Coleman Resume");

        btn_Intro.setText("Introduction");
        btn_Intro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IntroActionPerformed(evt);
            }
        });

        btn_Education.setText("Education");
        btn_Education.setName(""); // NOI18N
        btn_Education.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EducationActionPerformed(evt);
            }
        });

        btn_EducationalExp.setText("Educational Experience");
        btn_EducationalExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EducationalExpActionPerformed(evt);
            }
        });

        btn_Goals.setText("Goals");
        btn_Goals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GoalsActionPerformed(evt);
            }
        });

        btn_WorkHistory.setText("Work History");
        btn_WorkHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_WorkHistoryActionPerformed(evt);
            }
        });

        btn_ProfessionalExp.setText("Professional Experience");
        btn_ProfessionalExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProfessionalExpActionPerformed(evt);
            }
        });

        btn_About.setText("About Me");
        btn_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AboutActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jScrollPane2.setViewportView(Output);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_Code.setText("Code for this program");
        btn_Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CodeActionPerformed(evt);
            }
        });

        btn_Theme.setText("Theme");
        btn_Theme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Theme)
                        .addGap(333, 333, 333)
                        .addComponent(btn_Intro)
                        .addGap(18, 18, 18)
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Code))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Education, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_EducationalExp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Goals, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_WorkHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_ProfessionalExp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_About, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(title)
                        .addComponent(btn_Intro))
                    .addComponent(btn_Code)
                    .addComponent(btn_Theme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Education, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_EducationalExp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Goals, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_WorkHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ProfessionalExp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_About, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EducationActionPerformed
        //Education. High school, Undergrad and grad college
        clearOutput();

        dashes("Valencia High School");
        out("Attended from 2001 to 2005");
        out("I received my GED, finishing with a GPA of 3.0");
        out("A few techonology based classes I took were: Video Production, Tech core, Keyboarding, Computer Applications, and Home Page Production");
        out("During this time I also completed a few college courses: Introduction to the Game Industry, Introduction to the Internet, Windows File & Disk Management, and PowerPoint");
        lf();

        dashes("DeVry University");
        out("Attended from July 2006 to April 2011");
        out("I received my Bachelor's of Science in Game and Simulation Programming, finishing with a GPA of 3.3");
        out("A few notable classes I took were: System Architecture, Object-Oriented Programming, Technical Writing, Practical Game and Design, and Connectivity");
        lf();

        dashes("Walden University");
        out("Attended from November 2011 to February 2014");
        out("I received my Master's of Science in Information Systems, finishing with a GPA of 3.3");
        out("A few notable classes I took were: Enterprise System Architecture, Systems Analysis, Operating Systems & Network Architect, Advanced Software Development, and Data Modeling & Database Design");
        lf();
    }//GEN-LAST:event_btn_EducationActionPerformed

    private void btn_EducationalExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EducationalExpActionPerformed
        //Experience. List languages learned and classes taken
        clearOutput();

        dashes("Programming Concepts/Languages Learned");
        out("I learned programming logic while attending DeVry.  We utilized Vizio to visualize and organize code, as well as write pseudocode.");
        out("I have basic knowledge of C++ as I took one class.");
        out("I have a little development experience with HTML and CSS. Using Apache and notepad, I built a couple basic pages.");
        out("Most of my educational experience comes from Object Oriented programming.  PHP was my first experience with this, and I found that it came very naturally to me.");
        lf();

        dashes("Software Experience");
        out("The first IDE I used was Visual Studio, however we primarily used Notepad to write our code.");
        out("We used GIMP to edit graphic files, as it is a free solution to cover a lot of Photoshop's features.");
        lf();

        dashes("Achievements");
        out("I finished with a 3.3 GPA in both my Bachelor's and Master's programs.");
        out("At DeVry, I was on the Dean's List in 2006, 2008, 2009, and 2010.");
        lf();

    }//GEN-LAST:event_btn_EducationalExpActionPerformed

    private void btn_WorkHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_WorkHistoryActionPerformed
        //Work history, starting with data entry at DataQuick and Wesco
        clearOutput();

        dashes("Wesco Aircraft - Data Entry - Valencia, CA (2005)");
        out("My first real job was simple data entry.  I input aircraft part orders from a paper filing system into a database.");
        out("I worked here for about 6 months.  We moved from Valencia to Palmdale, so I resigned from the position to relocate and find a job closer to home.");
        lf();

        dashes("DataQuick - Data Entry - Palmdale, CA (2005-2006)");
        out("My second job was another data entry position, this time using coupons and contest entry forms taken from magazines to input to a database.");
        out("We used an old data entry keyboard called a System I data entry keyboard.");
        out("I worked here for about a year and a half.  The company was beginning to lose business, and eventually the business closed down.");
        lf();

        dashes("DeVry University - IT Help Desk - West Hills/Sherman Oaks, CA (2006-2008)");
        out("My third job was working as a student aid at the IT Help Desk at DeVry.");
        out("I did various tasks, such as assisting students and faculty with software/hardware issues and setting up rooms and labs with computers and software.");
        out("The largest task was the transition from West Hills to Sherman Oaks - we packed every computer, all lab equipment, and our server, and brought it over to the new Sherman Oaks campus.");
        out("Everything needed to be organized and labeled properly to ensure minimal disruption to the students.  We successfully transitioned everything over one weekend, starting Friday and having classrooms ready for Monday.");
        out("Eventually I re-located back with my mother to Minnesota to be closer to my family.  I was able to continue my education with DeVry online.");
        lf();

        dashes("Microsoft Inc. (Arvato Digital Services) - Customer Service - Valencia, CA (2010-2011");
        out("After the economy crashed, we needed to move back to California.  Shortly after moving back, I found a job working for a vendor of Microsoft's services named Arvato Digital Services.");
        out("This was a customer service position for billing and general product assistance for Microsoft's Online Services (now known as Office 365)");
        out("I assisted clients and partners with using the services, as well as any commerce related questions they had.");
        out("Eventually I worked my way up to a Quality Coach, in which I listened to the recorded interactions between our agents and our clients to score them based on metrics provided by Microsoft.");
        out("When I finished school, I decided to take some time off from work to celebrate my accomplishments and enjoy life until deciding my next step.");
        lf();

        dashes("Intuit (Digital Insight) - Customer Service - Westlake Village, CA (2012-2014)");
        out("Soon after starting school again, it was clear I needed another job.  Hoping this time to get into something more IT related, I reached out to some Temp Agencies who specialized in technical positions.");
        out("I started working for Digital Insight as a temp, and eventually earned my permanent position.  This was a customer service position dealing with an Online Banking platform provided and supported by Intuit.");
        out("During my stay with the company, Intuit sold us to a marketing company named Thoma Bravo.  A few months later, we were sold to another company named NCR Corporation.");
        out("Toward the end of earning my Master's Degree, I decided the customer service world was not my ideal job.  I left this position to take some time to find a job that was more suited for my career and interests.");
        lf();

        dashes("Motion Pictures Association of America - Internet Intelligence/Technical Analyst - Sherman Oaks, CA (2014-2016");
        out("Later that year, I began working for the MPAA as an Internet Intelligence/Technical Analyst.");
        out("I worked in the Content Protection department, which focused on implementing and executing strategies related to fighting the war on piracy of media owned by the 6 studios under the MPAA.");
        out("These 6 studios were Warner Bros., Disney, Paramount, Sony Pictures, Universal, and Fox.");
        out("I developed tools and bots to assist us in our research, as well as utilizing various white hat hacking techniques (such as penatration testing and packet tracing).");
        out("Unfortunately, as the MPAA had several offices around the world, and piracy is not as prevalent in the United States as it was, MPAA began to lay employees off from my team.  This prompted me to begin searching for another job.  Eventually, my entire team was let go.");
        lf();

        dashes("Regal Medical Group - Business Analyst - Northridge, CA (2016)");
        out("My most recent job was here as a Business Analyst.  We had people with various skill sets on my team, from those experienced in developing ad-hoc reports, to building databases, to building and maintaining periodic reports.");
        out("My first major task was to develop a database for another team, to schedule and maintain appointments for discharged patients following an urgent care or Emergency Room visit.");
        out("It took me about a month and a half using Access and SQL to build this database.  It was primarily used by two employees, with a few others using it for reporting purposes.");
        out("Here I also developed ad-hoc reports for various deparments and doctors using our databases and warehouses of data.");
        out("Unfortunately, living in Canyon Country and commuting to Northridge during rush hour times caused about 1-2 hours on average of commute time.  On some busy days, this was between 3-4 hours.  I left this position in the hopes of finding something closer, or finding a more managable situation.");
        lf();
        
        dashes("Adstream - Level 2 Technical Support/Solutions Architect Engineer - Burbank, CA (2016-Present)");
        out("I was hired as a Level 2 Technical Support agent, to support various clients with our online digital content delivery/storage/management system.  As we obtained more clients in the United States, custom workflows needed to be developed, which lead to my promotion to 'Solutions Architect Engineer'.");
        out("In Support, I investigated logs of user/system activity, investigated and fixed issues with various workflows, maintained a database of files, and supported in the processing of these files by clients or internal teams around the world.");
        out("As a Solutions Architect Engineer, I have developed a workflow for a client to facilitate the modification of metadata across various files, as well as helped design some of the onboarding processes of new clients.");
        out("I also developed a very rudimentary, but working e-mail tool for outage notifications.  While the tool was not used, it set in motion the creation of a newer e-mail tool.");
        out("The day-to-day of working here has taught me many things about myself and my career.  I learned a lot of technical skills and how to have a creative mindset when creating solutions.");
        lf();
    }//GEN-LAST:event_btn_WorkHistoryActionPerformed

    private void btn_ProfessionalExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProfessionalExpActionPerformed
        //Professional Experience. Languages I've used, what I prefer to use, what I'm good at, etc
        clearOutput();

        dashes("Analytical Skills");
        out("I have solid experience reviewing and analyzing websites generated with HTML, PHP, and JavaScript.  As JavaScript is a bit more difficult to parse than HTML and PHP, I utilized Selenium to automate the different JavaScript functions and report back to me with the changed code.");
        out("I was able to utilize Selenium together with my tools to inject searches into pirate sites and locate illegal content into some sites that were built with JavaScript with the intent of being more difficult to parse.");
        out("As piracy has expanded to mobile platforms as well, I was tasked with reading and analyzing underlying JavaScript and C code for connections and sources.  I met some success with this.");
        out("I also have experience with analyzing business requirements and practices with the intent of incorporating them into a new system.");
        lf();

        dashes("Languages");
        out("My most comfortable languages are C#, VB, Java, and PHP.  I have developed several tools and applications using these languages.");
        out("I used C# to develop a simple template-filler for certain interactions with customers working for Microsoft.  This was developed during my free time, and was not considered built by the company, so it ended up not being usable.");
        out("I used VB to build macros in Excel and different functions and dimensions in Access.");
        out("I use Java for my tool development researching pirate sites and locating pirated content.  I also use Java for my own projects to help automate random tasks, such as downloading an updated file and backing up the outdated one.");
        out("Most of my experience with PHP is in reading and parsing.  I have, however, used PHP to create dummy sites for various purposes.");
        out("I also have some standard experience with SQL, SQL Server, Crystal Reports, JavaScript, and a tiny bit of C++.");
        lf();

        dashes("Development");
        out("The majority of my experience is with Object Oriented Programming.  I feel as though it comes very naturally to me, though I know I still have a lot to learn.");
        out("I have developed two databases - one to schedule and maintain appointments following an Urgent Care/Emergency Room visit, and one to track productivity for a customer service team.");
        out("I have also developed a number of tools, including a Google Search assistant, Bot Search Injector, HTML Parser, Web Scraper, Cyberlocker Search Injector, and League of Legends Game Assistant.");
        out("I am working on developing my own game, a project that I have worked on and off for roughly 15 years.  This has changed engines quite a few times and is sadly not very far into development.");
        lf();

        dashes("Software");
        out("I have experience developing in a completely raw text-based environment, such as notepad, however I also have experience with Netbeans and Visual Studio.");
        out("I have expert experience in Excel - I am able to write formulas and macros to automate tasks and populate data.  I am also proficient in creating pivot tables, graphs, and charts.");
        out("I am also proficient in PowerPoint, Word, and Access.");
        lf();
    }//GEN-LAST:event_btn_ProfessionalExpActionPerformed

    private void btn_GoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GoalsActionPerformed
        //Goals.  Where do I want to be ideally?
        clearOutput();

        dashes("As a child, my dream job was");
        out("As a child, I wanted to be a game developer.  I have always been fascinated by how you can make a complete interactive world using nothing but text.");
        out("I wrote the instructions to my first game when I was 2 using my mother's typewriter.");
        lf();

        dashes("Growing up");
        out("Growing up I liked spending time writing notes and mapping out how I want to build my games.");
        out("I began using programs like RPG Maker, RPG Toolkit, and DarkBASIC.  I needed more development training to do anything serious, but I had fun and spent a lot of time learning what type of logic is needed for game development.");
        lf();

        dashes("Now that I have started my career");
        out("I found that I really enjoy programming in general.  I still would prefer to develop games if the situation were to arise, however I find a lot of satisfaction and enjoyment out of seeing my projects come to life.");
        out("I have always found programming logic to come naturally to me, so I have a lot of fun learning how to improve my knowledge and create more complex programs and processes.");
        out("I would like to further my knowledge of development, as I feel like the sky is the limit.  It would be a dream scenario to one day have the knowledge and resources to start my own Game Development company.");
        lf();
    }//GEN-LAST:event_btn_GoalsActionPerformed

    private void btn_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AboutActionPerformed
        //About me. Explain my experience with computers and technology in general, accomplishments, and side projects
        clearOutput();

        dashes("About Me");
        out("I am 31 years old.  I was born in northern Minnesota in a town called Two Harbors, with a population of around 3,000 people.");
        out("When I was 10, I moved out to southern California with my mother.  She felt my primary interest was in computers and technology, which is something our little town could not offer in the 90's.  Technology in general was a little outdated in Minnesota.");

        dashes("Strengths");
        out("I think my three biggest strengths are my attention to detail, my work ethic, and my passion to provide a positive outcome.");
        out("I really enjoy the process of working towards building a system to fill in business procedure gaps and shortcomings.  To see where a company may need help in improving or implementing a new procedure, and seeing my tools fix the solution so the business can run more efficiently is what motivates me to make the highest quality product I can.");
        out("I enjoy being a work horse as I enjoy driving results and staying ahead of development - it is much easier to stay organized and attack specific issues when deadlines have already been met.");
        out("My primary goal when working on any project, is to keep the end result and client's expectations at the forefront of my mind, to ensure that all requirements are met first, and improvements can be made second.");
        
        dashes("Weaknesses");
        out("I think my three biggest weaknesses are my experience, my work ethic, and my drive to be as close to perfect as possible.");
        out("When learning something new, I like to ensure I have done proper research and have developed the skill enough, before I put serious effort into using the skill to produce something.  I feel if I cannot provide a top quality product, there is little reason to try.");
        out("This has been both a blessing and a curse, as I feel I am the complete opposite of 'fake it til you make it' and will put forth the highest effort possible to make my product the best it can be.");
        out("Having a good work ethic can be a weakness as well, as it can lead to burning out.  Having said that, I feel I am most effective when I am writing code.  It doesn't feel much like a job, so I tend to go for hours without realizing it.");
        out("Lastly, I would say I have a lot of patience when it comes to developing something, however it may take me longer than usual on some things, as I try to take my time and get things as close to perfect as I can.  I still ensure to meet deadlines, but it is also natural for me to sneak in every minute I can to make the product the best I can.  To do this effectively, I make very good use of my time.");
        
        lf();
    }//GEN-LAST:event_btn_AboutActionPerformed

    private void btn_ThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemeActionPerformed
        changeTheme();
        out("Nothing yet :(");
    }//GEN-LAST:event_btn_ThemeActionPerformed

    private void btn_IntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IntroActionPerformed
        clearOutput();
        dashes("Introduction");
        out("Thank you for taking the time to download and view my resume!  I sincerely appreciate your time and the opportunity to show to you what I can offer to your organization.");
        out("I decided to write this application as a small example of my abilities, and a brief overview of who I am and my motivations.  If you have any questions, please feel free to contact me by phone at 661-481-4254, or by email at bcolema61@gmail.com.");
    }//GEN-LAST:event_btn_IntroActionPerformed

    private void btn_CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CodeActionPerformed
        out("Nothing yet :(");
    }//GEN-LAST:event_btn_CodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Output;
    private javax.swing.JButton btn_About;
    private javax.swing.JButton btn_Code;
    private javax.swing.JButton btn_Education;
    private javax.swing.JButton btn_EducationalExp;
    private javax.swing.JButton btn_Goals;
    private javax.swing.JButton btn_Intro;
    private javax.swing.JButton btn_ProfessionalExp;
    private javax.swing.JButton btn_Theme;
    private javax.swing.JButton btn_WorkHistory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
